name: provider_web
description: Forked from original provider package. A mixture between dependency injection and state management, built with widgets for widgets.
version: 0.0.1
homepage: https://github.com/damondouglas/provider_web

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  pedantic: ^1.4.0
  mockito: ^4.0.0
  flutter_web_test: any
  test: ^1.6.5


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
