name: example
version: 1.0.0
homepage: https://github.com/rrousselGit/provider	
author: Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  provider:

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  flutter_web_test: any

dependency_overrides:
  provider:
    path: ../
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

flutter:
  uses-material-design: true
